"""initial: users and profiles

Hand-written rather than autogenerated. The first migration is the one
autogenerate handles worst (enum types especially), and it is worth having
one readable migration in the repo to pattern-match against.

Revision ID: 0001
Revises:
Create Date: 2026-07-19
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Native Postgres enum types, created explicitly so ordering is obvious
    # and downgrade() can drop them cleanly.
    #
    # create_type=False is load-bearing: without it, referencing these same
    # objects in create_table() below makes SQLAlchemy emit a second
    # CREATE TYPE and the migration dies on "type stance already exists".
    stance = postgresql.ENUM("regular", "goofy", name="stance", create_type=False)
    skate_style = postgresql.ENUM("vert", "street", "mix", name="skate_style", create_type=False)
    stance.create(op.get_bind(), checkfirst=True)
    skate_style.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("cognito_sub", sa.String(64), nullable=True),
        sa.Column("username", sa.String(30), nullable=False),
        sa.Column("display_name", sa.String(60), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        # S3 key, not a URL — see CLAUDE.md conventions.
        sa.Column("avatar_key", sa.String(512), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        # The unique constraint supplies the lookup index for JWT -> user
        # resolution; a separate index on the same column would be redundant.
        sa.UniqueConstraint("cognito_sub", name="uq_users_cognito_sub"),
    )

    # Case-insensitive username uniqueness without the citext extension.
    # Also serves as the lookup index for /u/{username} profile URLs.
    op.create_index(
        "ix_users_username_lower",
        "users",
        [sa.text("lower(username)")],
        unique=True,
    )

    op.create_table(
        "profiles",
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("stance", stance, nullable=True),
        sa.Column("style", skate_style, nullable=True),
        sa.Column("board", sa.String(80), nullable=True),
        sa.Column("board_size", sa.Numeric(4, 2), nullable=True),  # inches, e.g. 8.25
        sa.Column("wheels", sa.String(80), nullable=True),
        sa.Column("wheel_size", sa.Integer(), nullable=True),  # mm
        sa.Column("trucks", sa.String(80), nullable=True),
        sa.Column("bearings", sa.String(80), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
    )


def downgrade() -> None:
    op.drop_table("profiles")
    op.drop_index("ix_users_username_lower", table_name="users")
    op.drop_table("users")
    # Enum types are not dropped with the tables that use them.
    postgresql.ENUM(name="skate_style").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="stance").drop(op.get_bind(), checkfirst=True)
